// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class User
    {
        public User()
        {
            BlogPosts = new HashSet<BlogPost>();
        }

        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime? CakeDay { get; set; }

        public virtual ICollection<BlogPost> BlogPosts { get; set; }
    }
}